#!/usr/bin/env python3

# Conceitos Notas
# A         De 10, a 9,1
# A-        De 9,0 a 8,1
# B         De 8,0 a 7,1
# B-        De 7,0 a 6,1
# C         De 6,0 a 5,1
# C-        De 5,0 a 4,1
# D         De 4,0 a 3,1
# D-        De 3,0 a 2,1
# E         De 2,0 a 1,1
# E-        De 1,0 a 0
# Para notas maiores que 10, ou menores que 0, imprimir "Nota inválida"
import math


if __name__ == "__main__":
    noto = input(
        "Entajpu valoron de noto, kaj vidu, al kiu litero ĝi ekvivalentas: ").replace(",", ".")

    def erarmesaĝo():
        print("Nevalida valoro! Entajpu valoron numeran por la noto, inter 0 kaj 10")

    try:
        noto = float(noto)
        if 0 < noto <= 1:
            print("Via noto, litere: E-")
        elif 1 < noto <= 2:
            print("Via noto, litere: E")
        elif 2 < noto <= 3:
            print("Via noto, litere: D-")
        elif 3 < noto <= 4:
            print("Via noto, litere: D")
        elif 4 < noto <= 5:
            print("Via noto, litere: C-")
        elif 5 < noto <= 6:
            print("Via noto, litere: C")
        elif 6 < noto <= 7:
            print("Via noto, litere: B-")
        elif 7 < noto <= 8:
            print("Via noto, litere: B")
        elif 8 < noto <= 9:
            print("Via noto, litere: A-")
        elif 9 < noto <= 10:
            print("Via noto, litere: A")
        else:
            erarmesaĝo()

    except ValueError:
        erarmesaĝo()
