#!/usr/bin/env python3
import math
import sys
import errno


class TerminalColor:
    ERARE = '\033[91m'
    NORMALE = '\033[0m'


def help_mesaĝilo():
    print('Necesas informi la valoron de radiuso')
    print(f'Ekz-e: {sys.argv[0]} <valoro>')


def cirklo(radiuso):
    return math.pi * float(radiuso) ** 2


if __name__ == '__main__':
    if len(sys.argv) < 2:
        help_mesaĝilo()
        sys.exit(errno.EPERM)
    elif not sys.argv[1].isnumeric():
        help_mesaĝilo()
        print(TerminalColor.ERARE +
              'Radiuso necesas esti numera valoro. '
              + TerminalColor.NORMALE)
    else:
        radiuso = float(sys.argv[1])
        areo = cirklo(radiuso)
        print(f'La areo de la cirklo estas {areo}')
