#!/usr/bin/env python3
import math


def cirklo(radiuso):
    return math.pi * float(radiuso) ** 2


if __name__ == '__main__':
    radiuso = float(input('Bv. enigi valoron de radiuso: '))
    areo = cirklo(radiuso)
    print(f'La areo de la cirklo estas {areo}')
